### ISSUE TITLE
Rosetta error when building m8c

### ISSUE THREAD

**Issue by kleincomplex** [jamesMcMeex/m8c-rg35xx-knulli#2]
Using Docker Desktop 4.34.2 (167172).

I'm seeing an error during the build process. Some searching suggests /lib64/ld-linux-x86-64.so.2
 is either not installed or corrupted somehow. 

`Configuring toolchain...`
`Building m8c...`
`aarch64-buildroot-linux-gnu-gcc -c -o src/main.o src/main.c  -D_REENTRANT -I/build/aarch64-buildroot-linux-gnu_sdk-buildroot/aarch64-buildroot-linux-gnu/sysroot/usr/include/SDL2 -Wall -Wextra -O2 -pipe -I.`
`rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2`
` make: *** [Makefile:23: src/main.o] Trace/breakpoint trap`

Any ideas are appreciated!

**Comment by jamesMcMeex** [comment]
It looks like an error that is caused by Rosetta on ARM-based Macs. You might need to run

```sh
docker buildx build --platform linux/amd64 -t m8c-knulli .
```

I've developed this on an old Intel-based Mac, which is the significant difference, I think.

Let me know how it goes

**Comment by kleincomplex** [comment]
That worked! Thank you so much

**Comment by jamesMcMeex** [comment]
Huge! Very glad this worked. I'm going to revisit this soon and hopefully make the scripts more flexible overall
