### ISSUE TITLE
Can't quit m8c

### ISSUE THREAD

**Issue by DRCRecoveryData** [jamesMcMeex/m8c-rg35xx-knulli#6]
Hi,

m8c can't quit by M button and Select button

I read on reddit that m8c quit by Memu button and Select button but not working, can you check this issue?

**Comment by jamesMcMeex** [comment]
I provided some instructions to someone on Reddit on how to remap the m8c controls here:

https://www.reddit.com/r/m8tracker/comments/1fk049w/comment/lo0qfis/

For my set up, I moved `SHIFT` to Y and `PLAY` to X. You can then do Start + Y to exit m8c

**Comment by DRCRecoveryData** [comment]
> I provided some instructions to someone on Reddit on how to remap the m8c controls here:
> 
> https://www.reddit.com/r/m8tracker/comments/1fk049w/comment/lo0qfis/
> 
> For my set up, I moved `SHIFT` to Y and `PLAY` to X. You can then do Start + Y to exit m8c

Before:
```
[gamepad]

gamepad_select=4
...
gamepad_quit=5
...
```

After:
```
[gamepad]

gamepad_select=5
...
gamepad_quit=4
...
```

Working quit by M button an Select button
