### ISSUE TITLE
"docker run" gives error on MacOS

### ISSUE THREAD

**Issue by maxkolenko** [jamesMcMeex/m8c-rg35xx-knulli#9]
I have an error at the step 4 on MacOS 15.1 when executing the following line:
`docker run -v $(pwd)/output:/build/compiled m8c-knulli  `
The error says:
`rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2`
I tried to search for the fix and added "--platform=linux/amd64" to the first line of Dockerfile:
`FROM --platform=linux/amd64 ubuntu:22.04`
After that `docker run` executed without errors.

**Comment by jamesMcMeex** [comment]
Before you continue, do you need to build the project? Unless you're doing some dev or debugging, you don't need to run the project - you can just use the compiled release here: https://github.com/jamesMcMeex/m8c-rg35xx-knulli/releases/tag/v1.0.0

I think we fixed this one already but let me know if you still have issues. Bear in mind I don't have access to other machines, only and M-series Mac, so I can't really test other platforms - that's down to you!
